sudo: required
language: python
services:
  - docker
before_install:
- docker build -t zbarlight .
- docker run -v "$TRAVIS_BUILD_DIR:/dist" zbarlight
# script:
# - bundle exec rake test
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
